### ISSUE TITLE
抓包问题

### ISSUE THREAD

**Issue by shgdym** [azhan1998/sam_buy#1]
trackinfo 这个变量看起来是在/commitPay 这里使用的, 应该是/commitPay这里抓包吧
请问/commitPay是在哪一步的抓包 因为火爆一直没抓到

**Comment by azhan1998** [comment]
getCapacityData里一些关于配送的项，要修改一些true或者false。以便于进入订单页面

**Comment by thethirdfive** [comment]
山姆app 是采用了ssl pining 吗，使用一般的https抓都是无网络，请问需要逆向吗？

**Comment by thethirdfive** [comment]
> 山姆app 是采用了ssl pining 吗，使用一般的https抓都是无网络，请问需要逆向吗？

已解决，换用了charles，配置好ios证书信任就可以抓到了

**Comment by azhan1998** [comment]
ok,我用的是ios，网球

**Comment by poctopus** [comment]
> > 山姆app 是采用了ssl pining 吗，使用一般的https抓都是无网络，请问需要逆向吗？
> 
> 已解决，换用了charles，配置好ios证书信任就可以抓到了

能说明一下在那一步能获取到commitPay接口，我跑了一遍下单，都没有获取到这个接口。

**Comment by azhan1998** [comment]
下单提示 配送已经满了，就会获取commitPay

**Comment by ohyummy** [comment]
iOS app试了一遍下单的流程，也没有抓到这个接口... 
是要在小程序里吗？

**Comment by azhan1998** [comment]
getCapacityData里一些关于配送的项，要修改一些true或者false。以便于进入订单页面
