### ISSUE TITLE
好兄弟，我的代码里怎么没有expect arrival time

### ISSUE THREAD

**Issue by Yoki0516** [azhan1998/sam_buy#10]
难道是要选上那个时间才能有这一段吗，没有的话怎么解决呢

**Comment by azhan1998** [comment]
> 难道是要选上那个时间才能有这一段吗

是的， 看看代码的注释和其他issues

**Comment by Yoki0516** [comment]
我都看过了，抱歉刚刚可能没表达清楚，修改点4里面有处是修改exceptarrivaltime为deliveryrealtime，但是我抓包里没有出现except….time，是否需要先用传统抢菜方法（蹲点）把配送时间填上再抓包？

**Comment by azhan1998** [comment]
修改getCapacityData()返回体中的 timeISFull=false, timeISFull=false,disable=true 即可选择配送时间 进行下单获得commitPay的参数
"expectArrivalTime":startRealTime,
 "expectArrivalEndTime":endRealTime,

**Comment by Yoki0516** [comment]
大佬牛逼，所有的包都抓到了，但是填写上去不知道规不规范，弱弱问一句请问跑起来是开始数数1 2 3 4 5吗……

**Comment by azhan1998** [comment]
4嗯嗯， getCapacityData里边有一个if not判断，你可以把not先删掉 看看返回是否正确；应该显示的是xxx配送时间已满之类的。。
一切正常 就还原回去
