### ISSUE TITLE
关于库存修改

### ISSUE THREAD

**Issue by nz5pro** [azhan1998/sam_buy#12]
“关于库存修改： timeISFull=false, timeISFull=false,disable=true 即可选择配送时间 进行下单获得commitPay的参数”

测试下来，如果是disable=true则只能看到时间但选不了时间，没法下一步进行commitpay， 改成disable=false即可

**Comment by funnyData** [comment]
你们是用什么软件来修改响应值的

**Comment by gulugulu999** [comment]
> “关于库存修改： timeISFull=false, timeISFull=false,disable=true 即可选择配送时间 进行下单获得commitPay的参数”
> 
> 测试下来，如果是disable=true则只能看到时间但选不了时间，没法下一步进行commitpay， 改成disable=false即可

我也遇到这个问题了，请问大神是怎么解决的？

**Comment by Fatreo** [comment]
> 

timisfull和dateisfull都要改成false

**Comment by NotwoJack** [comment]
> “关于库存修改： timeISFull=false, timeISFull=false,disable=true 即可选择配送时间 进行下单获得commitPay的参数”
> 
> 测试下来，如果是disable=true则只能看到时间但选不了时间，没法下一步进行commitpay， 改成disable=false即可

按这样设置返回后，时间还是显示不了。环境：mac端微信小程序

**Comment by azhan1998** [comment]
检查修改是否成功，实测charles和 http catcher 可以成功修改

**Comment by AlexSeven77** [comment]
> 检查修改是否成功，实测charles和 http catcher 可以成功修改

http catacher是在dns劫持还是在哪修改呢？
