### ISSUE TITLE
Max retries exceeded with url:*

### ISSUE THREAD

**Issue by whisperle** [azhan1998/sam_buy#14]
请问各位大神出现这个需要怎么处理？

**Comment by whisperle** [comment]
HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/delivery/portal/getCapacityData (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Comment by azhan1998** [comment]
把你的抓包工具关掉再运行python
