### ISSUE TITLE
优化了下下单流程

### ISSUE THREAD

**Issue by BranZhang** [azhan1998/sam_buy#2]
试了下，代码是能用的。

我稍微改进了下下单的流程：
1. 通过 `getUserCart` 接口获取当前购物车内的有效商品。不然 `commitPay` 接口中的商品和实际账户购物车中的商品不一致，会导致`commitPay` 接口返回“购物车商品有变动”的错误信息。又或者某些商品缺货了会导致下单失败。
2. 先请求 `getCapacityData` 接口，选择一个可用并且晚一点的配送时间，然后短时间内不断的用这个配送时间去请求 `commitPay` 接口，这样能提高一些成功的几率。

**Comment by azhan1998** [comment]
我把你添加到这个库的开发者了，更新一下代码吧。阿里嘎多~

**Comment by BranZhang** [comment]
不了。山姆这两天已经把上海的配送停了。

**Comment by azhan1998** [comment]
> 大佬们 怎么进入commitPay方法啊

看代码兄嘚。。

**Comment by azhan1998** [comment]
> 不了。山姆这两天已经把上海的配送停了。

山姆补货了，把你的贴一下吧

**Comment by hanlz** [comment]
> 

请问已付款的订单有配送吗，我这一直显示待发货

**Comment by azhan1998** [comment]
今天下单的也送到了啊，宝山

**Comment by hanlz** [comment]
了解，昨天下单的现在还没配送，可能是浦东这边太紧张了

**Comment by funnyData** [comment]
> 了解，昨天下单的现在还没配送，可能是浦东这边太紧张了

我这边也一直显示待配送，已经过了快2天了，坐标浦东
