### ISSUE TITLE
getAmount [Error]: name 'amount' is not defined

### ISSUE THREAD

**Issue by nathan-guo** [azhan1998/sam_buy#20]
目前有库存：味好美(McCormick) 咖喱粉调料 500g	#数量：1	#金额：33.8元
LIMITED当前购物火爆，请稍后再试
getAmount [Error]: name 'amount' is not defined

Process finished with exit code 0

**Comment by azhan1998** [comment]
fixed now

**Comment by 910466892** [comment]
请问trackinfo的问题是不是被修复了，现在还需要更改getCapacityData()的参数获取trackinfo吗？
