### ISSUE TITLE
有成功抢到了么？

### ISSUE THREAD

**Issue by qzqsmile** [azhan1998/sam_buy#3]
RT

**Comment by Yuanyezz** [comment]
同问

**Comment by shgdym** [comment]
成功了2次 都是上午十点半左右

**Comment by gulugulu999** [comment]
请问安卓环境如何抓包？ ios上成功了，但是通过小程序抓包的。app登录受限了，

**Comment by azhan1998** [comment]
安卓抓包不太清楚，ios很easy

**Comment by Fatreo** [comment]
想问一下，这个是会自动下单，然后需要自己去手机里支付的吗？

**Comment by gulugulu999** [comment]
> 安卓抓包不太清楚，ios很easy

在iso上一直抓不到commitPay，请问必须到支付页面才能抓到么

**Comment by Fatreo** [comment]
> > 安卓抓包不太清楚，ios很easy
> 
> 在iso上一直抓不到commitPay，请问必须到支付页面才能抓到么

进入选择四种支付方式的时候就可以抓到了，改一下前面getCapacityData就可以进到

**Comment by poctopus** [comment]
> > > 安卓抓包不太清楚，ios很easy
> > 
> > 
> > 在iso上一直抓不到commitPay，请问必须到支付页面才能抓到么
> 
> 进入选择四种支付方式的时候就可以抓到了，改一下前面getCapacityData就可以进到

说说一下trackinfo填写的具体格式吗？

**Comment by Fatreo** [comment]
> > > > 安卓抓包不太清楚，ios很easy
> > > 
> > > 
> > > 在iso上一直抓不到commitPay，请问必须到支付页面才能抓到么
> > 
> > 
> > 进入选择四种支付方式的时候就可以抓到了，改一下前面getCapacityData就可以进到
> 
> 说说一下trackinfo填写的具体格式吗？

我这边抓到的是这样的 不知道对不对
'[{"labelType":"push_trace","attachId":""},{"labelType":"systemMessage_trace","attachId":""},{"labelType":"apppushmsgtaskid_trace","attachId":""},{"labelType":"systemmsgtasksubid_trace","attachId":""},{"labelType":"tracking_id","attachId":"1649822857351-0D2F7C88-4211-45CF-8D29-760B1CF73CCC"},{"labelType":"tracepromotion","createTime":"","attachId":""}]'

**Comment by gulugulu999** [comment]
把getCapacityData接口的response.body里一些关于库存的true或false修改一下就可以进入到commitPay方法获取trackinfo和data.

请问如何在quantumult里面修改呢？

**Comment by poctopus** [comment]
> > > > > 安卓抓包不太清楚，ios很easy
> > > > 
> > > > 
> > > > 在iso上一直抓不到commitPay，请问必须到支付页面才能抓到么
> > > 
> > > 
> > > 进入选择四种支付方式的时候就可以抓到了，改一下前面getCapacityData就可以进到
> > 
> > 
> > 说说一下trackinfo填写的具体格式吗？
> 
> 我这边抓到的是这样的 不知道对不对 '[{"labelType":"push_trace","attachId":""},{"labelType":"systemMessage_trace","attachId":""},{"labelType":"apppushmsgtaskid_trace","attachId":""},{"labelType":"systemmsgtasksubid_trace","attachId":""},{"labelType":"tracking_id","attachId":"1649822857351-0D2F7C88-4211-45CF-8D29-760B1CF73CCC"},{"labelType":"tracepromotion","createTime":"","attachId":""}]'

和我的一样，是直接把这些内容直接贴在trackinfo中吗？

**Comment by gulugulu999** [comment]
长时间运行会遇到：

getCapacityData [Error]: HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/delivery/portal/getCapacityData (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

有人遇到同样问题么？

**Comment by poctopus** [comment]
> 长时间运行会遇到：
> 
> getCapacityData [Error]: HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/delivery/portal/getCapacityData (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
> 
> 有人遇到同样问题么？

用最新的脚本运行了505次，正常的，没有报错。

帮忙确认一下trackinfo是怎么填写的，是不是这样的？
trackinfo= '[{"labelType":"push_trace","attachId":""},{"labelType":"systemMessage_trace","attachId":""},{"labelType":"apppushmsgtaskid_trace","attachId":""},{"labelType":"systemmsgtasksubid_trace","attachId":""},{"labelType":"tracking_id","attachId":"1649816626519-686EFCD5-CCD3-4B12-94DB-C8F9870491A3"},{"labelType":"tracepromotion","createTime":"","attachId":""}]'

**Comment by Fatreo** [comment]
> 长时间运行会遇到：
> 
> getCapacityData [Error]: HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/delivery/portal/getCapacityData (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
> 
> 有人遇到同样问题么？

遇到过 不用管它 过一会就可以继续了。或者关了再开一样

**Comment by gulugulu999** [comment]
> 

我还是老老实实进入anaconda就好了

**Comment by nz5pro** [comment]
> > 长时间运行会遇到：
> > getCapacityData [Error]: HTTPSConnectionPool(host='api-sams.walmartmobile.cn', port=443): Max retries exceeded with url: /api/v1/sams/delivery/portal/getCapacityData (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))
> > 有人遇到同样问题么？
> 
> 遇到过 不用管它 过一会就可以继续了。或者关了再开一样
请问代码正常跑如果没抢到是否是输出下面的文字？


{'strDate': '2022/04/14 周四', 'deliveryDesc': '', 'deliveryDescEn': '', 'dateISFull': True, 'list': [{'startTime': '09:00', 'endTime': '15:00', 'timeISFull': True, 'disabled': False, 'closeDate': '2022-04-13', 'closeTime': '21:00', 'startRealTime': '1649898000000', 'endRealTime': '1649919600000'}, {'startTime': '15:00', 'endTime': '21:00', 'timeISFull': True, 'disabled': False, 'closeDate': '2022-04-14', 'closeTime': '11:00', 'startRealTime': '1649919600000', 'endRealTime': '1649941200000'}]}

**Comment by azhan1998** [comment]
嗯嗯， getCapacityData里边有一个if not判断，你可以把not先删掉 看看返回是否正确；应该显示的是xxx配送时间已满之类的。。
一切正常 就还原回去

**Comment by nz5pro** [comment]
> 删掉not 后运行结果如下，看下是否正确，并未显示xxx配送时间已满

{'strDate': '2022/04/14 周四', 'deliveryDesc': '', 'deliveryDescEn': '', 'dateISFull': True, 'list': [{'startTime': '09:00', 'endTime': '15:00', 'timeISFull': True, 'disabled': False, 'closeDate': '2022-04-13', 'closeTime': '21:00', 'startRealTime': '1649898000000', 'endRealTime': '1649919600000'}, {'startTime': '15:00', 'endTime': '21:00', 'timeISFull': True, 'disabled': False, 'closeDate': '2022-04-14', 'closeTime': '11:00', 'startRealTime': '1649919600000', 'endRealTime': '1649941200000'}]}
【成功】获取配送时间
下单：1649898000000
{"data":{},"code":"RECEIVER_TIME_EMPTY","msg":"收货时间为空","errorMsg":"","traceId":"","requestId":"a989598d1266424dba005b00d3c59491.1041.16498424427748665","rt":0,"clientIp":null,"success":false}
下单：1649898000000

**Comment by azhan1998** [comment]
收货时间为空 检查你的commitpay body ，看看我注释的怎么写的

**Comment by nz5pro** [comment]
> 收货时间为空 检查你的commitpay body ，看看我注释的怎么写的

 # 修改点4： 抓包替换为自己的 修改 expectArrivalTime为startRealTime ； expectArrivalEndTime 为endRealTime
 # 修改点4中的一项注意修改"expectArrivalTime":startRealTime "expectArrivalEndTime":endRealTime ：

抱歉新手多包涵！

这两个的意思是否为：把commitpay 的respond body 里面的expectArrivalTime替换成startRealTime ，expectArrivalEndTime改为endRealTime即可？这个是不是收货时间的参数？

例如抓包内容为 
 "expectArrivalTime": "1649919600000",
"expectArrivalEndTime ": "1649941200000",

就改成
"startRealTime": "1649919600000",
"endRealTime ": "1649941200000",

**Comment by ontheway01** [comment]
> 把getCapacityData接口的response.body里一些关于库存的true或false修改一下就可以进入到commitPay方法获取trackinfo和data.
> 
> 请问如何在quantumult里面修改呢？



请教，怎么修改的。我用的streem没法编辑响应体

**Comment by qzqsmile** [comment]
> 成功了2次 都是上午十点半左右

上午十点半那个应该是捡漏了，目测一般是晚上九点放开

**Comment by Fatreo** [comment]
这样不会被ban吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月13日(星期三) 晚上9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [azhan1998/sam_buy] 有成功抢到了么？ (Issue #3)





   
成功了2次 都是上午十点半左右
  
上午十点半那个应该是捡漏了，目测一般是晚上九点放开。多谢LZ，我也来试试
  
不好说 我是从前一天下午开始挂的, 我把代码里的sleep去掉了
 
&mdash;

**Comment by jonaszhouC** [comment]
> 成功了2次 都是上午十点半左右

能教一下怎么抓的包么。。fiddler抓app显示无网络

**Comment by gulugulu999** [comment]
> 

请问getCapacityData里边有一个if not判断，在哪里？ 是const myRequest下面嘛？

**Comment by gulugulu999** [comment]
> > > 
> > 
> > 
> > 请问getCapacityData里边有一个if not判断，在哪里？ 是const myRequest下面嘛？
> 
> 哎呀 代码就一句if not，你搜索一下 ：）

我发现为啥抓不到commitPay了，修改了timeIsFull等字段后依然无效，其实是因为我用的山姆app版本不一样。。。您应该用的不是最新版app吧

**Comment by gulugulu999** [comment]
山姆把bug给修了

**Comment by azhan1998** [comment]
百度查询ios app降级，下载v5.0.45.1
