### ISSUE TITLE
Two issue found

### ISSUE THREAD

**Issue by zhongyefan** [azhan1998/sam_buy#32]
1. isOpenTime = ([20, 10].**index**(now.hour) > -1 and [57, 58, 59].index(now.minute) > -1
                                  or [21, 11].index(now.hour) > -1 and now.minute < 6)
List index() 如果不存在会直接抛出 ValueError: xxx is not in list. 因此or之后的21:00-21:05和11：00-11:05将不会进入判断。

2. status0 = (myRet['data'].get('capcityResponseList')[0].get('dateISFull'))只考虑了可配送日期的唯一选项，而没有考虑到多个配送日期，可能会导致出现一天满但另一天有时间情况下无法下单

*Improvement advice
可在下单成功后除音乐外添加smtp邮件发送，并在邮件中添加链接，以便第一时间知道下单成功并操作付款

**Comment by azhan1998** [comment]
已修改
isOpenTime = ([20, 10].index(now.hour) > -1 and [ 58, 59].index(now.minute) > -1 or [21, 11].index(now.hour) > -1 and now.minute < 2)

**Comment by jxs0112** [comment]
# bug fix 【1，2】用于白天全城配，【3，4】用于晚上全城配，【5，6】用于极速达
                open_time_1 = datetime.datetime.strptime(str(now.date()) + '10:58', '%Y-%m-%d%H:%M')
                open_time_2 = datetime.datetime.strptime(str(now.date()) + '11:02', '%Y-%m-%d%H:%M')
                open_time_3 = datetime.datetime.strptime(str(now.date()) + '20:58', '%Y-%m-%d%H:%M')
                open_time_4 = datetime.datetime.strptime(str(now.date()) + '21:02', '%Y-%m-%d%H:%M')
                open_time_5 = datetime.datetime.strptime(str(now.date()) + '07:58', '%Y-%m-%d%H:%M')
                open_time_6 = datetime.datetime.strptime(str(now.date()) + '08:02', '%Y-%m-%d%H:%M')
                is_open_time = open_time_1 < now < open_time_2 or open_time_3 < now < open_time_4 or open_time_5 < now < open_time_6
