### ISSUE TITLE
fiddler everywhere要怎么加这段自定义脚本哇

### ISSUE THREAD

**Issue by TUANZHANGDDD** [azhan1998/sam_buy#33]
公司电脑搞不了 自己电脑身上只有mac 没装虚拟机 有mac版的fiddler everywhere 怎么加这个自定义脚本哇（和win版长得不一样真没找到这个功能）大佬们 抢菜党哭了

**Comment by alanleung2017** [comment]
> 公司电脑搞不了 自己电脑身上只有mac 没装虚拟机 有mac版的fiddler everywhere 怎么加这个自定义脚本哇（和win版长得不一样真没找到这个功能）大佬们 抢菜党哭了

留一下你的邮箱地址

**Comment by TUANZHANGDDD** [comment]
@azhan1998 2351169265@qq.com

**Comment by TUANZHANGDDD** [comment]
2351169265@qq.com

**Comment by TUANZHANGDDD** [comment]
***@***.***


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: ALan Leung ***@***.***&gt;
发送时间: 2022年4月20日 13:38
收件人: azhan1998/sam_buy ***@***.***&gt;
抄送: TUANZHANGDDD ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[azhan1998/sam_buy] fiddler everywhere要怎么加这段自定义脚本哇 (Issue #33)





  
公司电脑搞不了 自己电脑身上只有mac 没装虚拟机 有mac版的fiddler everywhere 怎么加这个自定义脚本哇（和win版长得不一样真没找到这个功能）大佬们 抢菜党哭了
  
留一下你的邮箱地址

**Comment by peterparker2077** [comment]
> 公司电脑搞不了 自己电脑身上只有mac 没装虚拟机 有mac版的fiddler everywhere 怎么加这个自定义脚本哇（和win版长得不一样真没找到这个功能）大佬们 抢菜党哭了

macos 你用charles这个软件抓包
