### ISSUE TITLE
fiddler怎么抓不到包

### ISSUE THREAD

**Issue by showlcw** [azhan1998/sam_buy#35]

**Comment by vvvsrx** [comment]
用Charles

**Comment by showlcw** [comment]
Charles 使用Android手机还是不行。。  必须IOS吗

**Comment by peterparker2077** [comment]
> Charles 使用Android手机还是不行。。 必须IOS吗

不是的，跟手机系统和电脑系统都无关，证书安装好就能抓https的包了

**Comment by showlcw** [comment]
搞定了   使用模拟器 root下  然后把fiddler证书安装到系统层级就行了  多谢
