### ISSUE TITLE
购物车请求头中没有trackinfo字段可以不填或者填个什么默认的吗

### ISSUE THREAD

**Issue by kailiu119** [azhan1998/sam_buy#39]
POST /api/v1/sams/goods-portal/spu/queryUserCartPage HTTP/1.1
Host: api-sams.walmartmobile.cn
Content-Type: application/json
Accept: */*
auth-token: 740d926b981716f4aa5cdd429513e15311dc44fbbdd109de9a576c2087e13b69
app-version: 5.0.48.3
longitude: 121.609515
device-id: 72768d274b548d75bc0af6f7000012214c11
latitude: 31.262697
device-type: ios
Accept-Language: zh-Hans-CN;q=1
Accept-Encoding: gzip, deflate, br
apptype: ios
device-name: iPhone_12
device-os-version: 15.3.1
User-Agent: SamClub/5.0.48 (iPhone; iOS 15.3.1; Scale/3.00)
Content-Length: 629
system-language: CN
Connection: keep-alive

{"addressDTO":{"detailAddress":"****","cityName":"上海市","countryName":"中国","districtName":"浦东新区","provinceName":"上海市"},"userUid":"181813808094","uid":"ED53D94E-A8F5-4EE3-B615-5B3DD0D3CE9A","pageNum":1,"channelType":1,"storeInfo":[{"storeId":"9991","storeType":"32","storeDeliveryAttr":[10]},{"storeId":"6988","storeType":"2","storeDeliveryAttr":[3,12]},{"storeId":"6683","storeType":"4","storeDeliveryAttr":[3,4]},{"storeId":"9996","storeType":"8","storeDeliveryAttr":[1]}],"appIO":"ios","userCard":"10742210513262816","spuId":"1282191","uidType":3,"appVersion":"5.0.48.3","pageSize":20}

请求头如上，问题如题

**Comment by tedyyu** [comment]
看看 /getusercart 这个请求

**Comment by kailiu119** [comment]
> 看看 /getusercart 这个请求

找到了多谢
