### ISSUE TITLE
trackinfo这个变量没有明白是怎么抓取的

### ISSUE THREAD

**Issue by lxbbb** [azhan1998/sam_buy#4]
RT

**Comment by azhan1998** [comment]
有注释呀代码里

**Comment by nz5pro** [comment]
这个是抓到的commitpay的JSONtext，找不到trackinfo这个变量，另外修改点4里的除了goodslist 里的spuId 、storeId、以及提到的startRealTime和endRealTime之外，其他的还需要替换吗？

{
	"sceneCode": 1001,
	"deliveryInfoVO": {
		"storeType": 2,
		"storeDeliveryTemplateId": "552578721878546198",
		"deliveryModeId": "1003"
	},
	"storeInfo": {
		"areaBlockId": "300128585287607062",
		"storeId": "4807",
		"storeType": 2
	},
	"channel": "wechat",
	"invoiceInfo": {},
	"isSelectShoppingNotes": true,
	"addressId": "143451905",
	"cartDeliveryType": 2,
	"couponList": [],
	"floorId": 1,
	"goodsList": [{
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1278313",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10011856", "10011857"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 小青柠汁饮料 1L*2",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/4205093/b3b34249-6261-4c9b-8c9f-f1ab39a49b19.jpg",
		"quantity": 1,
		"purchaseLimitVO": null,
		"minPurchaseLimitVO": null,
		"stockQuantity": 353,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "3480",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "424528",
		"hostUpc": ["6941330900469", "0", "0", "0"],
		"sevenDaysReturn": false,
		"addCartTime": "1649588047611",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": null,
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 2.2,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "21084426",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003290", "10005220"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 巧克力咖啡卷 12片",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/4277914/56a9ec36-780f-48df-86fc-ef8eaa777135_719420220210191213328IMG_37911.jpg",
		"quantity": 1,
		"purchaseLimitVO": {
			"limitType": 5,
			"limitNum": 1,
			"storeId": "4807",
			"residuePurchaseNum": 1,
			"text": "限购1件",
			"popupText": "每单限购1件, 您还可购买1件"
		},
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "6800",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "981011889",
		"hostUpc": ["2169374000004"],
		"sevenDaysReturn": false,
		"addCartTime": "1649563890317",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": "限购1件",
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 1.3,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [{
			"id": null,
			"title": "限购1件",
			"tagPlace": 5,
			"tagMark": null
		}],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1283336",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003229", "10004682"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 澳洲进口谷饲牛腩1kg",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/3548290/662728af-3915-4ead-bb6d-269096a3579b.jpg",
		"quantity": 4,
		"purchaseLimitVO": null,
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "8960",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "980037097",
		"hostUpc": ["2168098000000", "2898003709703", "2168098000000", "2168098000000"],
		"sevenDaysReturn": false,
		"addCartTime": "1649561794023",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": null,
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 1,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1279223",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003290", "10005220"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 原味伯爵瑞士卷 16片",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/3548338/38b5b017-373e-45d1-b489-1d70231493a9_6375202106301834415341.jpg",
		"quantity": 1,
		"purchaseLimitVO": {
			"limitType": 5,
			"limitNum": 1,
			"storeId": "4807",
			"residuePurchaseNum": 1,
			"text": "限购1件",
			"popupText": "每单限购1件, 您还可购买1件"
		},
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "6800",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "980062312",
		"hostUpc": ["2168438000004", "2168438000004", "2168438000004", "2168438000004"],
		"sevenDaysReturn": false,
		"addCartTime": "1648973249447",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": "限购1件",
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 1.59,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [{
			"id": null,
			"title": "限购1件",
			"tagPlace": 5,
			"tagMark": null
		}],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1277950",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003290", "10005220"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 黄油巧克力卷12个",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/3262777/fc28f88d-a27f-4b9f-bd92-a819c3aeb15b.jpg",
		"quantity": 2,
		"purchaseLimitVO": null,
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "3980",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "980025758",
		"hostUpc": ["2167924000009", "2167924000009", "2167924000009", "2167924000009"],
		"sevenDaysReturn": false,
		"addCartTime": "1648973221815",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": null,
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 1,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1282924",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003290", "10005220"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 黄油大羊角面包 9个",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/3965266/fb356e78-2092-48ce-9155-d4830975d60c.jpg",
		"quantity": 2,
		"purchaseLimitVO": null,
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "2980",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "980025756",
		"hostUpc": ["2167923000000", "2167923000000", "2167923000000", "2167923000000"],
		"sevenDaysReturn": false,
		"addCartTime": "1648973120655",
		"deliveryTagId": null,
		"promotionTag": "比加入时降￥7.0元",
		"minPurchaseTag": null,
		"goodsLimitTag": null,
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 0.33,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [{
			"id": null,
			"title": "比加入时降￥7.0元",
			"tagPlace": 5,
			"tagMark": null
		}],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}, {
		"storeId": "4807",
		"storeType": 2,
		"spuId": "1282975",
		"skuId": null,
		"brandId": "10194688",
		"categoryIdList": ["10003023", "10003290", "10005220"],
		"masterBizType": 1,
		"viceBizType": null,
		"goodsName": "MM 原味麻薯面包 24个",
		"goodsImage": "https://sam-material-online-1302115363.file.myqcloud.com//sams-static/goods/3548296/9e675196-fee9-4f64-b1ad-21441cca5668_6496202106301817011071.jpg",
		"quantity": 3,
		"purchaseLimitVO": null,
		"minPurchaseLimitVO": null,
		"stockQuantity": 9999,
		"stockStatus": true,
		"isPutOnSale": true,
		"isAvailable": true,
		"price": "3580",
		"originPrice": "0",
		"deliveryAttr": 3,
		"hostItem": "980063973",
		"hostUpc": ["2168493000001", "2168493000001", "2168493000001", "2168493000001"],
		"sevenDaysReturn": false,
		"addCartTime": "1648973118731",
		"deliveryTagId": null,
		"promotionTag": "",
		"minPurchaseTag": null,
		"goodsLimitTag": null,
		"warrantyExtensionList": [],
		"giveawayList": null,
		"weight": 0.8,
		"emg": null,
		"isSelected": true,
		"isCollected": false,
		"isPreSell": false,
		"isRoutine": true,
		"ticketId": null,
		"payTotalPrice": null,
		"discountTotalPrice": null,
		"realSinglePrice": null,
		"invalidReason": null,
		"labelList": null,
		"beltInfo": null,
		"componentPath": null,
		"cartDeliveryType": null,
		"tagInfo": [],
		"deliveryTypeList": [],
		"orderAmt": "77580",
		"payAmt": 0
	}],
	"amount": 77580,
	"currency": "CNY",
	"orderType": 0,
	"payMethodId": "contract",
	"payType": 0,
	"remark": "",
	"shortageDesc": "其他商品继续配送（缺货商品直接退款）",
	"shortageId": 1,
	"labelList": "[{\"attachId\":\"1649682167516-b844981c-d7ed-45e5-9476-c5ac25298df3\",\"createTime\":1649682167810,\"labelType\":\"tracking_id\"},{\"attachId\":1001,\"createTime\":1649682167811,\"labelType\":\"scene_xcx\"}]",
	"settleDeliveryInfo": {
		"deliveryType": 2,
		"deliveryDesc": "",
		"deliveryName": "2022/04/12 周二",
		"expectArrivalEndTime": 1649768400000,
		"expectArrivalTime": 1649746800000
	},
	"uid": "18189023467",
	"appId": "wxb344a8213bcaf849",
	"saasId": "1524"
}

**Comment by svcvit** [comment]
trackinfo 在herader 里

**Comment by nz5pro** [comment]
> trackinfo 在herader 里
我用的微信sam小程序抓包，在header里抓不到这个trackinfo。是因为微信小程序抓不到这个嘛？苹果手机没有开发者帐号能玩吗？

POST /api/v1/sams/trade/settlement/commitPay HTTP/1.1
Host: api-sams.walmartmobile.cn
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36 MicroMessenger/7.0.9.501 NetType/WIFI MiniProgramEnv/Windows WindowsWechat
auth-token: *
content-type: application/json;charset=utf-8
device-type: mini_program
system-language: CN
Referer: https://servicewechat.com/wxb344a8513eaaf849/228/page-frame.html
Accept-Encoding: gzip, deflate, br
Content-Length: 9669

**Comment by poctopus** [comment]
用charles还是抓不到commitPay这个接口，各位有啥方法。

**Comment by azhan1998** [comment]
> > trackinfo 在herader 里
> > 我用的微信sam小程序抓包，在header里抓不到这个trackinfo。是因为微信小程序抓不到这个嘛？苹果手机没有开发者帐号能玩吗？
> 
> POST /api/v1/sams/trade/settlement/commitPay 

用ios客户端试试吧

**Comment by poctopus** [comment]
修改了getCapacityData的相关参数后，获取到了trackinfo信息，但是在在脚本中填写的trackinfo是xxxxxxxx-xxxx-xxx-xxxx-xxxx-xxxxxxxx这样的字符串吗？

**Comment by jonaszhouC** [comment]
求教学一下怎么抓的 我用fiddler 手机app进去无网络。

**Comment by AlexSeven77** [comment]
我也没搞明白trackInfo这个参数怎么获取的，这两天都无法模拟到commitPay这个请求。按理来说，trackInfo应该是前面某个接口的Header里带进来的吧

**Comment by BecomerichAsun** [comment]
> 

直接改getCapacityData 返回值 把时间弄出来 就能commitpay了 兄弟

**Comment by azhan1998** [comment]
同意楼上，
