### ISSUE TITLE
这个is_open_time是出于什么目的的哦？

### ISSUE THREAD

**Issue by Zmnortal** [azhan1998/sam_buy#43]
我看了下代码 发现这个is_open_time会在三个重要的时间点周围进行了sleep
感觉这样设计很奇怪啊 难道不是反而要在这段时间内去抢的么 不然东西不就被抢光了？

**Comment by azhan1998** [comment]
仔细阅读代码好吗？ 已经在火爆时间缩短sleep时间了。 不sleep等着被ban嘛:)
