### ISSUE TITLE
时间拿到了 但是报错

### ISSUE THREAD

**Issue by BecomerichAsun** [azhan1998/sam_buy#7]
name 'true' is not define

**Comment by azhan1998** [comment]
把ture 改成'true'

**Comment by Yoki0516** [comment]
我也是，把ifnot的 not去掉后显示

1
{'strDate': '2022/04/14 周四', 'deliveryDesc': '', 'deliveryDescEn': '', 'dateISFull': True, 'list': [{'startTime': '15:00', 'endTime': '21:00', 'timeISFull': True, 'disabled': False, 'closeDate': '2022-04-14', 'closeTime': '11:00', 'startRealTime': '1649919600000', 'endRealTime': '1649941200000'}]}
【成功】获取配送时间
下单：1649919600000
getCapacityData [Error]: name 'true' is not defined

请问name true是怎么解决的

**Comment by azhan1998** [comment]
看楼上

**Comment by Yoki0516** [comment]
大佬你好！没找到ture啊，我全搜索过了，true在货物清单那堆代码里倒是有的，可否说的再详细一点呢

**Comment by Yoki0516** [comment]
哦，我懂了
